CREATE SCHEMA gorillablog;

USE gorillablog;

CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(256) NOT NULL,
  post TEXT NOT NULL,
  category TEXT NOT NULL,
  PRIMARY KEY (id)
);
